"""agents and templates for the marketplace

Revision ID: 8603d8ed3e6d
Revises: 64cd62b3c93c
Create Date: 2026-08-15 11:52:24.441485

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8603d8ed3e6d'
down_revision: Union[str, None] = '64cd62b3c93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('splitter', sa.String(length=32), nullable=False),
    sa.Column('retrieve_k', sa.Integer(), nullable=False),
    sa.Column('rerank_enabled', sa.Boolean(), nullable=False),
    sa.Column('rerank_top_n', sa.Integer(), nullable=False),
    sa.Column('score_threshold', sa.Float(), nullable=False),
    sa.Column('max_rewrites', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('splitter', sa.String(length=32), nullable=False),
    sa.Column('retrieve_k', sa.Integer(), nullable=False),
    sa.Column('rerank_enabled', sa.Boolean(), nullable=False),
    sa.Column('rerank_top_n', sa.Integer(), nullable=False),
    sa.Column('score_threshold', sa.Float(), nullable=False),
    sa.Column('max_rewrites', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('generation_model', sa.String(length=128), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['agent_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name')
    )
    op.create_index(op.f('ix_agents_owner_user_id'), 'agents', ['owner_user_id'], unique=False)
    op.add_column('chunks', sa.Column('asset_uri', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('agent_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.create_index(op.f('ix_documents_agent_id'), 'documents', ['agent_id'], unique=False)
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'user_id')
    op.add_column('queries', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_queries_agent_id'), 'queries', ['agent_id'], unique=False)
    op.create_foreign_key(None, 'queries', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_index(op.f('ix_queries_agent_id'), table_name='queries')
    op.drop_column('queries', 'agent_id')
    op.add_column('documents', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_documents_agent_id'), table_name='documents')
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_column('documents', 'uploaded_by_user_id')
    op.drop_column('documents', 'agent_id')
    op.drop_column('chunks', 'asset_uri')
    op.drop_index(op.f('ix_agents_owner_user_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
